### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by iamrasheeq** [saurabh-m-w/Blockchain-Based-Property-Registration#5]

**Comment by iamrasheeq** [comment]
> No description provided.

**Comment by saurabh-m-w** [comment]
Hey,is the issue solved?  First Contract owner has to add land inspector using land inspector's public key,then using that account land inspector can login.

**Comment by iamrasheeq** [comment]
Hi, yes the issue is solved ☺️. We mistakenly put the AccountAddress
instead of ContractAddress. That's what creating the problem.
